In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/sentiment-analysis-dataset/Dropbox.csv

In [2]:
!pip install transformers

Requirement already satisfied: transformers in /opt/conda/lib/python3.10/site-packages (4.46.3)
Requirement already satisfied: filelock in /opt/conda/lib/python3.10/site-packages (from transformers) (3.15.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.26.2)
Requirement already satisfied: numpy>=1.17 in /opt/conda/lib/python3.10/site-packages (from transformers) (1.26.4)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.10/site-packages (from transformers) (21.3)
Requirement already satisfied: pyyaml>=5.1 in /opt/conda/lib/python3.10/site-packages (from transformers) (6.0.2)
Requirement already satisfied: regex!=2019.12.17 in /opt/conda/lib/python3.10/site-packages (from transformers) (2024.5.15)
Requirement already satisfied: requests in /opt/conda/lib/python3.10/site-packages (from transformers) (2.32.3)
Requirement already satisfied: tokenizers<0.21,>=0.20 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.20.3)
Requirement already satisfied: safetensors>=0.4.1 in /opt/conda/lib/python3.10/site-packages (from transformers) (0.4.5)
Requirement already satisfied: tqdm>=4.27 in /opt/conda/lib/python3.10/site-packages (from transformers) (4.66.4)
Requirement already satisfied: fsspec>=2023.5.0 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (2024.6.0)
Requirement already satisfied: typing-extensions>=3.7.4.3 in /opt/conda/lib/python3.10/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers) (4.12.2)
Requirement already satisfied: pyparsing!=3.0.5,>=2.0.2 in /opt/conda/lib/python3.10/site-packages (from packaging>=20.0->transformers) (3.1.2)
Requirement already satisfied: charset-normalizer<4,>=2 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (1.26.18)
Requirement already satisfied: certifi>=2017.4.17 in /opt/conda/lib/python3.10/site-packages (from requests->transformers) (2024.6.2)

In [3]:
import torch

In [4]:
df=pd.read_csv("/kaggle/input/sentiment-analysis-dataset/Dropbox.csv")
df.tail(20)

,reviewId,content,score
9980,e749c2aa-a006-4dcc-be92-c21d1d5b064a,Love this app had it for years.,5
9981,6ea8f9d4-4e7d-460d-b42a-89c11d5ec4d4,Ni e,5
9982,be862866-076e-48a9-80e6-58311ce59634,😒,1
9983,1f47539e-1657-4fa2-9f5b-e1d684675a6d,WHERE'S MY MUSIC? IT WAS THERE BEFORE?,3
9984,3db5cddd-da78-4c58-abb6-90631de46f25,very good application,5
9985,4b7e26f5-feb0-4868-8b31-9caf97ca7a47,Where is all my.files ...this this was so full...,2
9986,50145bb0-aa94-4913-9171-64a82699999f,Simple great,5
9987,0c9cf5a6-9704-45b0-8d20-6d5fa796c921,Really frustrating! I am being charged TWICE. ...,3
9988,b6c7db05-943c-471b-9fc7-30bdacda8c38,Wonderful,5
9989,be2e8bc2-0e9b-4849-9f55-bafc8904eb09,Easy to use. No problems so far :),5
9990,b041953b-8a6f-4b64-8a8d-9cecf55c718a,Don't install this app after long time use the...,1
9991,085c2e64-ecb1-47cd-ba0a-461faa650a1b,Why are you billing on trail?,1
9992,80a462e3-f90f-437b-b880-1173584c2b49,So far so gokd,5
9993,306f0fd8-aea6-4ed5-86c5-b2e26744c3e9,Great site. Helps you stay organized.,5
9994,48f2e57c-8b37-44bd-8d5b-edf64c24398f,"Have been using this for years, but other stor...",3
9995,1723b8cb-b5b7-49db-94a0-b8185f2007e6,The cream of the crop in easy peasy cloud stor...,5
9996,4f3288ed-6800-4f22-91f9-eb321a958487,not singing in from android mobile,3
9997,9a694712-d3b9-46b7-bcec-c3c0a7207029,After years of use I've decided to cancel my s...,1
9998,c96bd9ea-39b8-49f7-bb5d-de8f38a1adfc,awesome,5
9999,dfd445a2-0681-44dc-b446-e0abc0e70d59,Stop sending me these texts I am not intereste...,1

In [5]:
df.describe

<bound method NDFrame.describe of                                   reviewId  \
0     dafa8ee2-babc-423b-870e-2d9279cff01e
1     b4f40c25-41b5-4c97-b4cb-d35930a609e0
2     5505adff-9bae-439e-b242-698ea2a8482c
3     e6b4e364-30a8-423d-bf16-8aedd8493235
4     70257417-02ed-47a1-b1bb-b0079e9c86ae
...                                    ...
9995  1723b8cb-b5b7-49db-94a0-b8185f2007e6
9996  4f3288ed-6800-4f22-91f9-eb321a958487
9997  9a694712-d3b9-46b7-bcec-c3c0a7207029
9998  c96bd9ea-39b8-49f7-bb5d-de8f38a1adfc
9999  dfd445a2-0681-44dc-b446-e0abc0e70d59

                                                content  score
0     It's exactly what I need. A place for me to or...      5
1     تضمن كل ملفاتك وصورك محفوظه من التلف او الضياع...      5
2                                Meta WhatsApp business      5
3     Kudos to Dropbox app for an effective cloud st...      5
4            Great options for backups! plenty of space      5
...                                                 ...    ...
9995  The cream of the crop in easy peasy cloud stor...      5
9996                 not singing in from android mobile      3
9997  After years of use I've decided to cancel my s...      1
9998                                            awesome      5
9999  Stop sending me these texts I am not intereste...      1

[10000 rows x 3 columns]>

In [6]:
df=df.sample(200)
df

,reviewId,content,score
2792,7c252e16-0b77-4f93-9e4e-a01ce6bc0202,Good,5
6845,621fa3e4-35cb-4bd1-8265-f685a532cf77,I downloaded it as a photo backup service but ...,2
5334,6d1a8856-6dfd-45c8-87e5-6728f3fd10fc,Good,5
5202,cf318102-e2dd-4ba9-8d26-6902d3a366ca,😁😁😁,3
4593,9594eed6-2bf5-4f78-b490-28461f03faac,The Latest big Changes made a perfectly good a...,1
...,...,...,...
1000,41e86cdc-93eb-46ac-846c-41801d96128c,About photo,1
5972,e7b8d21e-4552-49d9-ae69-154108727e34,showing space used 13 GB vs actual use of 1.3 gb,3
3745,e27d2a47-2f3e-430d-847a-c91a8c650b8d,I signed up for a free trial with an upgrade t...,2
8484,f09c3440-ed1f-4dd3-b272-4c0e7b67950a,Good,5
9540,afbc87c0-969b-4a79-b489-edf77d6773b0,V gud,5

In [7]:
import torch
from transformers import AutoTokenizer, AutoModelForSequenceClassification, pipeline

In [11]:
model_name = "cardiffnlp/twitter-roberta-base-sentiment"
tokenizer = AutoTokenizer.from_pretrained(model_name)
model = AutoModelForSequenceClassification.from_pretrained(model_name).to("cuda")
nlp = pipeline("sentiment-analysis", model=model, tokenizer=tokenizer, device=0)

In [12]:
label_mapping = {
    "LABEL_0": "negative",
    "LABEL_1": "neutral",
    "LABEL_2": "positive"
}
texts = list(df.content.values)
results = nlp(texts)

for text, result, score in zip(texts, results, df.score.values):
    human_label = label_mapping[result["label"]]  
    print("Text:", text)
    print("Result:", {"label": human_label, "score": result["score"]})
    print("Score:", score)
    print("-" * 80)

Text: Good
Result: {'label': 'positive', 'score': 0.6097784638404846}
Score: 5
--------------------------------------------------------------------------------
Text: I downloaded it as a photo backup service but it doesn't seem to work right. It will backup photos for a while and then just stop. Since that was my primary reason for using the app, and it doesn't work, I give it a low rating and don't trust it with my precious photos.
Result: {'label': 'negative', 'score': 0.9294798970222473}
Score: 2
--------------------------------------------------------------------------------
Text: Good
Result: {'label': 'positive', 'score': 0.6097784638404846}
Score: 5
--------------------------------------------------------------------------------
Text: 😁😁😁
Result: {'label': 'positive', 'score': 0.8840939402580261}
Score: 3
--------------------------------------------------------------------------------
Text: The Latest big Changes made a perfectly good app almost useless. Before I could open any file direct into edit mode. (preferd) Now it goes into preview were I can see the whole file topp is cut off. Did MS buy it ?... Garbage app now give me 2022 app. I recommend using Chrome instead much much better. Files even open.. (response ask for details, Try excel files.. with the app ? on Android. latest uppdate destroyed a good product.)
Result: {'label': 'negative', 'score': 0.5756071209907532}
Score: 1
--------------------------------------------------------------------------------
Text: Frustrated with trying to cancel, jumping thru hoops to no avail!
Result: {'label': 'negative', 'score': 0.9048783779144287}
Score: 1
--------------------------------------------------------------------------------
Text: Reduced 10 gb to 5 gb saving space suddenly. Monthly plan is too costly. Google Drive yearly plan too much affordable.
Result: {'label': 'negative', 'score': 0.5382979512214661}
Score: 1
--------------------------------------------------------------------------------
Text: can't download an epub file.
Result: {'label': 'negative', 'score': 0.804452121257782}
Score: 1
--------------------------------------------------------------------------------
Text: Had to download to open a file. Why are we regressing with technology and having to download apps to access features I could use without an app previously
Result: {'label': 'negative', 'score': 0.6538147926330566}
Score: 1
--------------------------------------------------------------------------------
Text: This app sucks, it automatically deletes my .zip + .xml files although they're backups for app configurations... It also doesn't cancel uploads when i click cancel all, it kept uploading no matter how many times i clicked cancel... uninstalled for good!
Result: {'label': 'negative', 'score': 0.9488404393196106}
Score: 1
--------------------------------------------------------------------------------
Text: Nothing happened
Result: {'label': 'neutral', 'score': 0.6467056274414062}
Score: 5
--------------------------------------------------------------------------------
Text: Too expensive and they destabilize my devices
Result: {'label': 'negative', 'score': 0.9572592973709106}
Score: 1
--------------------------------------------------------------------------------
Text: the best
Result: {'label': 'positive', 'score': 0.8702048063278198}
Score: 5
--------------------------------------------------------------------------------
Text: Pretty solid... =}
Result: {'label': 'positive', 'score': 0.9284436106681824}
Score: 5
--------------------------------------------------------------------------------
Text: Once you start with them you're stuck if you don't upgrade you loose access to all your files and photos. (You are prisoner)
Result: {'label': 'negative', 'score': 0.6893587708473206}
Score: 1
--------------------------------------------------------------------------------
Text: I don't know what happened but DropBox (on PC and Phone) sucks, it won't let me create a new account because it says I already have one, so I say "Oh well then I'll just recover my password" it either says "this email hasn't been registered" or "too many attempts have been made on THIS DEVICE" I remark that said "THIS DEVICE" my phone, right? cuz I try recovering it in other devices and it will still tell me that, if you could fix this garbage of whatever the frick is happening it'll be amazing.
Result: {'label': 'negative', 'score': 0.8449848890304565}
Score: 1
--------------------------------------------------------------------------------
Text: Not easy to upgrade if have old email address
Result: {'label': 'negative', 'score': 0.7141839265823364}
Score: 3
--------------------------------------------------------------------------------
Text: smooth performance
Result: {'label': 'positive', 'score': 0.7157773375511169}
Score: 5
--------------------------------------------------------------------------------
Text: Good
Result: {'label': 'positive', 'score': 0.6097784638404846}
Score: 1
--------------------------------------------------------------------------------
Text: Please my dropbox account has been disable... i requested my acount open it... thank you
Result: {'label': 'neutral', 'score': 0.6209028959274292}
Score: 1
--------------------------------------------------------------------------------
Text: superior to google ?yes. but that is a low bar at this point. way too many aspects of dropbox are a maze of overly complicated convoluted randomness. it just took me half an hour to figure out where trash is , how to select files for deletion and i have to re enter my password every time i want to delete something. if you want this app to be more secure just make us use 2fa. making the user reenter their password every single time they want to delete something is absurd ane inefficient.
Result: {'label': 'negative', 'score': 0.7972689270973206}
Score: 3
--------------------------------------------------------------------------------
Text: Wd ed de ed s w d S v e. Iy
Result: {'label': 'neutral', 'score': 0.7450449466705322}
Score: 5
--------------------------------------------------------------------------------
Text: Can't sign in App just not respond Terrible
Result: {'label': 'negative', 'score': 0.9571117758750916}
Score: 1
--------------------------------------------------------------------------------
Text: Dropbox has Awful "Prices" for what you actually get with their "Service" compared to their competitors. DEFINITELY is NOT worth your time. or 💵 💰 💵 💰 💵 because there are Much BETTER Cloud Apps Available that you can USE, Especially over THIS APP. Give either "Mega" or "Box" Cloud Storage" a try, because they give way more functionality for their "Free Version" of their apps. then the PAID VERISON of Dropbox! 💯
Result: {'label': 'negative', 'score': 0.5566439628601074}
Score: 2
--------------------------------------------------------------------------------
Text: Think all of us sapose to be there tomorrow together for a while and be ready to leave now if you're still interested. . . call me?
Result: {'label': 'neutral', 'score': 0.5684177875518799}
Score: 5
--------------------------------------------------------------------------------
Text: Don't find it helpful. Trying to cancel. Can't figure it out.
Result: {'label': 'negative', 'score': 0.9473938345909119}
Score: 1
--------------------------------------------------------------------------------
Text: Could somebody contact me and refund my money for a service I don't use? Impossible to get ahold of anyone via email.
Result: {'label': 'negative', 'score': 0.8330501914024353}
Score: 1
--------------------------------------------------------------------------------
Text: good
Result: {'label': 'positive', 'score': 0.66302490234375}
Score: 5
--------------------------------------------------------------------------------
Text: Service is ok, app is missing all useful features. Can't sort, filter, search doesn't work, no criteria options, navigation is terrible. Was this app built for people with 5 files in their account?
Result: {'label': 'negative', 'score': 0.8786031007766724}
Score: 2
--------------------------------------------------------------------------------
Text: Uninstalled. Not useful
Result: {'label': 'negative', 'score': 0.9544172286987305}
Score: 1
--------------------------------------------------------------------------------
Text: Dropbox is an interesting app and awesome
Result: {'label': 'positive', 'score': 0.9876074194908142}
Score: 5
--------------------------------------------------------------------------------
Text: Hello, Thank you for contacting Proton Mail support. Your request (2065820) has been received and is being reviewed by our support staff. Please note that due to the heavy load of tickets, we might not be able to reply to your inquiry within the next 24 hours. In the meantime, if you are having login issues, you can find the solutions to the most common login problems on the following page:
Result: {'label': 'neutral', 'score': 0.5469683408737183}
Score: 5
--------------------------------------------------------------------------------
Text: Fantastic app , soul saver ,
Result: {'label': 'positive', 'score': 0.8532208204269409}
Score: 5
--------------------------------------------------------------------------------
Text: Signed up using one e-mail address & attempted to download a video using another email. Even after verifying the second email address, I was still unable to download after multiple attempts. Worthless!!! Please cancel my subscription immediately!
Result: {'label': 'negative', 'score': 0.9453807473182678}
Score: 1
--------------------------------------------------------------------------------
Text: superb ❤
Result: {'label': 'positive', 'score': 0.9242625832557678}
Score: 5
--------------------------------------------------------------------------------
Text: You can't create and edit files from app and from desktop. If you create it in desktop you can't edit it in app If you create in app, you cant edit in desktops
Result: {'label': 'negative', 'score': 0.5763804912567139}
Score: 1
--------------------------------------------------------------------------------
Text: App seems to be working better again now. Seems to be back to normal so it gets 4 stars now. I won't go back to 5 until I've forgotten the troubles I had with it.
Result: {'label': 'positive', 'score': 0.9057807922363281}
Score: 4
--------------------------------------------------------------------------------
Text: Crashes every time. Too bad, I love the idea and the security is great. Just wished it worked.
Result: {'label': 'positive', 'score': 0.3485250473022461}
Score: 2
--------------------------------------------------------------------------------
Text: I lost everything on my phone thanks for Dropbox I have all my pictures
Result: {'label': 'neutral', 'score': 0.45133382081985474}
Score: 5
--------------------------------------------------------------------------------
Text: It's very slow getting your pictures to come up!
Result: {'label': 'negative', 'score': 0.753242552280426}
Score: 2
--------------------------------------------------------------------------------
Text: Been using dropbox until yesterday 22 Aug 24, whereby the image thumbnail link when sending via whatsapp can be seen, now it just a blank image with my url link. Hopefully this can be fixed, other thumbnail image links in whatsapp eg: like YouTube, news link, works fine. Worst part, I cannot talk to everyone about my issue. Today, 24 Aug 24, this problem has resolved, hope it stays that way...changed my rating.
Result: {'label': 'neutral', 'score': 0.4167667329311371}
Score: 5
--------------------------------------------------------------------------------
Text: Good
Result: {'label': 'positive', 'score': 0.6097784638404846}
Score: 3
--------------------------------------------------------------------------------
Text: Always There for Me!
Result: {'label': 'positive', 'score': 0.8622991442680359}
Score: 5
--------------------------------------------------------------------------------
Text: Its secure enough for all my saved items and needs!
Result: {'label': 'positive', 'score': 0.8344200849533081}
Score: 5
--------------------------------------------------------------------------------
Text: Great, Very Useful App
Result: {'label': 'positive', 'score': 0.9735071659088135}
Score: 5
--------------------------------------------------------------------------------
Text: All my files and training videos are accessible easily anytime and anywhere.
Result: {'label': 'positive', 'score': 0.7980763912200928}
Score: 5
--------------------------------------------------------------------------------
Text: I dont use it
Result: {'label': 'negative', 'score': 0.5262178182601929}
Score: 3
--------------------------------------------------------------------------------
Text: I love it Yes
Result: {'label': 'positive', 'score': 0.9759028553962708}
Score: 5
--------------------------------------------------------------------------------
Text: Don't understand warning about upload expiry
Result: {'label': 'negative', 'score': 0.828476071357727}
Score: 3
--------------------------------------------------------------------------------
Text: nice app
Result: {'label': 'positive', 'score': 0.905877947807312}
Score: 5
--------------------------------------------------------------------------------
Text: This app is very good❤❤
Result: {'label': 'positive', 'score': 0.9923298954963684}
Score: 5
--------------------------------------------------------------------------------
Text: nice
Result: {'label': 'positive', 'score': 0.6387197375297546}
Score: 1
--------------------------------------------------------------------------------
Text: not always easy to excess files.
Result: {'label': 'neutral', 'score': 0.48433467745780945}
Score: 3
--------------------------------------------------------------------------------
Text: It's great 5 star
Result: {'label': 'positive', 'score': 0.9775682687759399}
Score: 5
--------------------------------------------------------------------------------
Text: 👍🙂
Result: {'label': 'positive', 'score': 0.7005802989006042}
Score: 5
--------------------------------------------------------------------------------
Text: Doesn't upload files when I want to.
Result: {'label': 'negative', 'score': 0.6175394058227539}
Score: 2
--------------------------------------------------------------------------------
Text: bit pricey
Result: {'label': 'neutral', 'score': 0.4786987006664276}
Score: 3
--------------------------------------------------------------------------------
Text: Good
Result: {'label': 'positive', 'score': 0.6097784638404846}
Score: 4
--------------------------------------------------------------------------------
Text: good
Result: {'label': 'positive', 'score': 0.66302490234375}
Score: 5
--------------------------------------------------------------------------------
Text: USER BEWARE!! I started a free trial and canceled it before my trial was up. Today, I found a charge on my account from them for $20. I have spent the past 2 hours trying to troubleshoot this issue on my end and can't get ahold of anyone without having a paid account. So, my basic account that should be FREE is charging me $20 a month. In order to get help, I now need to pay more? Makes no sense. Dropbox are thieves using dark patterns against their users, shame on you all.
Result: {'label': 'negative', 'score': 0.9459999203681946}
Score: 1
--------------------------------------------------------------------------------
Text: The absolute worst place to store your stuff. They give you so much free space to use but if you don't upgrade they delete your account without warning and you lose everything !!!
Result: {'label': 'negative', 'score': 0.9368593692779541}
Score: 1
--------------------------------------------------------------------------------
Text: Good
Result: {'label': 'positive', 'score': 0.6097784638404846}
Score: 5
--------------------------------------------------------------------------------
Text: A user friendly storage app. Very good for media storage.
Result: {'label': 'positive', 'score': 0.9667443633079529}
Score: 5
--------------------------------------------------------------------------------
Text: Ok
Result: {'label': 'neutral', 'score': 0.526487410068512}
Score: 5
--------------------------------------------------------------------------------
Text: Worse app I can't unlock file after download apk and register also they say reason of not permision
Result: {'label': 'negative', 'score': 0.9200345277786255}
Score: 1
--------------------------------------------------------------------------------
Text: It's a pretty good app and online service but what I do find annoying is the updates that don't indicate what has been updated or changed, I'm all for moving forward but it sounds as if whatever is being updated is cloaked in secrecy, please be transparent.
Result: {'label': 'negative', 'score': 0.5326133370399475}
Score: 4
--------------------------------------------------------------------------------
Text: I use this very rarely.
Result: {'label': 'neutral', 'score': 0.4996069073677063}
Score: 2
--------------------------------------------------------------------------------
Text: Worst app that even after I successfully cancel my free trial, still charge fee to my card. The worst part is they made the cancellation extremely difficult and the guide to cancel does not work.
Result: {'label': 'negative', 'score': 0.950591504573822}
Score: 1
--------------------------------------------------------------------------------
Text: Scam, hidden subscription fees, even if you uninstall the app, don't download, it is a scam.
Result: {'label': 'negative', 'score': 0.9499465823173523}
Score: 1
--------------------------------------------------------------------------------
Text: Use full
Result: {'label': 'neutral', 'score': 0.666114866733551}
Score: 5
--------------------------------------------------------------------------------
Text: Excellent App that makes photo sharing easy. A bit expensive but lots of options and tools make the price worth it.
Result: {'label': 'positive', 'score': 0.9473767280578613}
Score: 5
--------------------------------------------------------------------------------
Text: Stop trying to make everything a subscription.
Result: {'label': 'negative', 'score': 0.6859687566757202}
Score: 1
--------------------------------------------------------------------------------
Text: wish I could have Dropbox running in the background while music plays from it
Result: {'label': 'neutral', 'score': 0.6579446196556091}
Score: 3
--------------------------------------------------------------------------------
Text: Great app
Result: {'label': 'positive', 'score': 0.9504569172859192}
Score: 5
--------------------------------------------------------------------------------
Text: Not happy, I don't want to pay to use.
Result: {'label': 'negative', 'score': 0.9612890481948853}
Score: 1
--------------------------------------------------------------------------------
Text: nice
Result: {'label': 'positive', 'score': 0.6387197375297546}
Score: 5
--------------------------------------------------------------------------------
Text: Ok
Result: {'label': 'neutral', 'score': 0.526487410068512}
Score: 5
--------------------------------------------------------------------------------
Text: Good
Result: {'label': 'positive', 'score': 0.6097784638404846}
Score: 3
--------------------------------------------------------------------------------
Text: so far so good
Result: {'label': 'positive', 'score': 0.973818838596344}
Score: 5
--------------------------------------------------------------------------------